"""
CourseForge AI — Export Service
Responsibility: Generate Markdown and text export reports of student progress and analytics.
"""
from __future__ import annotations

from sqlalchemy.ext.asyncio import AsyncSession
from services.analytics_service import AnalyticsService


class ExportService:
    """Service to produce exportable summary reports."""

    def __init__(self, db: AsyncSession):
        self.db = db
        self.analytics_service = AnalyticsService(db)

    async def export_markdown_summary(self, user_id: str, course_id: str) -> str:
        """
        Generates clean Markdown export report.
        """
        analytics = await self.analytics_service.get_course_analytics(user_id, course_id)
        recommendations = await self.analytics_service.get_revision_recommendations(user_id, course_id)

        md = f"""# CourseForge AI — Learning Progress Summary Report

> **Generated Date**: {analytics.get('course_id')} | **Platform**: CourseForge AI v0.7.0

---

## 📊 Overview Metrics

- **Overall Course Completion**: {analytics.get('overall_progress_pct')}%
- **Lessons Completed**: {analytics.get('completed_lessons')} / {analytics.get('total_lessons')}
- **Total Study Time**: {analytics.get('total_time_spent_min')} minutes
- **Average Quiz Score**: {analytics.get('avg_quiz_score')}%
- **Flashcard Retention Rate**: {analytics.get('flashcard_retention_pct')}%
- **Learning Streak**: {analytics.get('learning_streak_days')} days in a row ⚡

---

## 🎯 Weak & Strong Topics

### ⚠️ Topics Needing Review
"""
        weak_topics = analytics.get("weak_topics", [])
        if weak_topics:
            for w in weak_topics:
                md += f"- **{w['title']}**: Quiz Score {w['score_pct']}%\n"
        else:
            md += "- None! You're performing well across all topics.\n"

        md += "\n### 🌟 Strongest Topics\n"
        strong_topics = analytics.get("strong_topics", [])
        if strong_topics:
            for s in strong_topics:
                md += f"- **{s['title']}**: Quiz Score {s['score_pct']}%\n"
        else:
            md += "- Complete quizzes to identify your strongest topics.\n"

        md += "\n---\n\n## 📝 Personalized Revision Plan\n\n"
        for rec in recommendations:
            md += f"### [{rec['priority'].upper()}] {rec['title']}\n"
            md += f"{rec['reason']}\n\n"

        md += "---\n*Export generated by CourseForge AI — Intelligent Learning Platform*\n"
        return md
