.PHONY: help build up down logs test-backend test-frontend lint format clean db-upgrade db-downgrade db-revision

help: ## Show this help
	@echo "CourseForge AI Development Commands"
	@echo "-----------------------------------"
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-20s\033[0m %s\n", $$1, $$2}'

# ─────────────────────────────────────────────
# Docker Commands
# ─────────────────────────────────────────────
build: ## Build all Docker containers
	cd docker && docker-compose build

up: ## Start all services in the background
	cd docker && docker-compose up -d

down: ## Stop all services and remove containers
	cd docker && docker-compose down

logs: ## Tail logs for all services
	cd docker && docker-compose logs -f

# ─────────────────────────────────────────────
# Testing & Quality
# ─────────────────────────────────────────────
test-backend: ## Run backend pytest suite
	cd backend && pytest ../tests/backend -v

test-frontend: ## Run frontend vitest suite
	cd frontend && npm run test

lint-backend: ## Run Ruff linter
	cd backend && ruff check .

lint-frontend: ## Run ESLint
	cd frontend && npm run lint

format: ## Format both backend (Ruff) and frontend (Prettier)
	cd backend && ruff format .
	cd frontend && npm run format

# ─────────────────────────────────────────────
# Database
# ─────────────────────────────────────────────
db-upgrade: ## Upgrade database to latest migration
	cd backend && alembic upgrade head

db-downgrade: ## Downgrade database by 1 revision
	cd backend && alembic downgrade -1

db-revision: ## Create a new autogenerated migration (Usage: make db-revision m="message")
	cd backend && alembic revision --autogenerate -m "$(m)"

# ─────────────────────────────────────────────
# Cleanup
# ─────────────────────────────────────────────
clean: ## Remove python cache files
	find . -type d -name "__pycache__" -exec rm -rf {} +
	find . -type d -name ".pytest_cache" -exec rm -rf {} +
	find . -type d -name ".ruff_cache" -exec rm -rf {} +
