import pytest
from unittest.mock import AsyncMock, MagicMock
from datetime import datetime, timezone

@pytest.mark.asyncio
async def test_get_cached_lesson(mocker):
    from services.lesson_generator import LessonGeneratorService

    mock_db = AsyncMock()

    mock_lesson = type(
        "Lesson",
        (),
        {
            "id": "l1",
            "course_id": "c1",
            "title": "Test Lesson",
            "summary": "Summary",
            "status": "ready",
            "content_markdown": "# Test Lesson\nContent here.",
            "version": 1,
        },
    )()

    mock_result = MagicMock()
    mock_result.scalar_one_or_none.return_value = mock_lesson
    mock_db.execute.return_value = mock_result

    mocker.patch("services.lesson_generator.InsightForgeEngine")

    service = LessonGeneratorService(mock_db)
    res = await service.generate_lesson("c1", "l1", force_regenerate=False)

    assert res.id == "l1"
    assert res.content_markdown == "# Test Lesson\nContent here."
    assert res.status == "ready"


@pytest.mark.asyncio
async def test_generate_new_lesson_content(mocker):
    from services.lesson_generator import LessonGeneratorService

    mock_db = AsyncMock()

    mock_lesson = type(
        "Lesson",
        (),
        {
            "id": "l1",
            "course_id": "c1",
            "title": "Introduction to Python",
            "summary": "Basics of Python programming",
            "status": "pending",
            "content_markdown": None,
            "version": 1,
            "estimated_duration_min": 15,
            "generation_error": None,
            "generated_at": None,
            "llm_metadata": None,
        },
    )()

    mock_course = type("Course", (), {"id": "c1", "title": "Python 101"})()
    mock_doc = type(
        "Document",
        (),
        {
            "course_id": "c1",
            "index_status": "ready",
            "insightforge_doc_id": "doc_123",
        },
    )()

    mock_result_lesson = MagicMock()
    mock_result_lesson.scalar_one_or_none.return_value = mock_lesson

    mock_result_course = MagicMock()
    mock_result_course.scalar_one_or_none.return_value = mock_course

    mock_result_doc = MagicMock()
    mock_result_doc.scalar_one_or_none.return_value = mock_doc

    mock_result_topics = MagicMock()
    mock_result_topics.scalars.return_value.all.return_value = []

    mock_db.execute.side_effect = [
        mock_result_lesson,
        mock_result_course,
        mock_result_doc,
        mock_result_topics,
    ]

    mock_engine_instance = mocker.patch("services.lesson_generator.InsightForgeEngine")

    mock_chunk = type("Chunk", (), {"content": "Python is an interpreted language."})()
    mock_engine_instance.return_value.retrieve_chunks.return_value = [mock_chunk]

    mock_query_result = type(
        "QueryResult",
        (),
        {"answer": "# Introduction to Python\n\nLesson text generated by AI."},
    )()
    mock_engine_instance.return_value.query.return_value = mock_query_result

    service = LessonGeneratorService(mock_db)
    res = await service.generate_lesson("c1", "l1", force_regenerate=False)

    assert res.status == "ready"
    assert res.content_markdown == "# Introduction to Python\n\nLesson text generated by AI."
